apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ploggi
  name: ploggi
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ploggi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ploggi
    spec:
      containers:
      - image: localhost:5000/ploggi:latest
        imagePullPolicy: Always
        name: ploggi
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccountName: ploggi
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ploggi
  name: ploggi
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 50051
  selector:
    app: ploggi
  sessionAffinity: None
  type: ClusterIP
