// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: pkg/api/ploggi/ploggi.proto

package ploggi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Podname       string `protobuf:"bytes,1,opt,name=podname,proto3" json:"podname,omitempty"`
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Containername string `protobuf:"bytes,3,opt,name=containername,proto3" json:"containername,omitempty"`
}

func (x *Pod) Reset() {
	*x = Pod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ploggi_ploggi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ploggi_ploggi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_pkg_api_ploggi_ploggi_proto_rawDescGZIP(), []int{0}
}

func (x *Pod) GetPodname() string {
	if x != nil {
		return x.Podname
	}
	return ""
}

func (x *Pod) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Pod) GetContainername() string {
	if x != nil {
		return x.Containername
	}
	return ""
}

type PodLog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Log string `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
}

func (x *PodLog) Reset() {
	*x = PodLog{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_ploggi_ploggi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodLog) ProtoMessage() {}

func (x *PodLog) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_ploggi_ploggi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodLog.ProtoReflect.Descriptor instead.
func (*PodLog) Descriptor() ([]byte, []int) {
	return file_pkg_api_ploggi_ploggi_proto_rawDescGZIP(), []int{1}
}

func (x *PodLog) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

var File_pkg_api_ploggi_ploggi_proto protoreflect.FileDescriptor

var file_pkg_api_ploggi_ploggi_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x6f, 0x67, 0x67, 0x69,
	0x2f, 0x70, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70,
	0x6c, 0x6f, 0x67, 0x67, 0x69, 0x22, 0x63, 0x0a, 0x03, 0x50, 0x6f, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x6f, 0x64, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70,
	0x6f, 0x64, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1a, 0x0a, 0x06, 0x50, 0x6f,
	0x64, 0x4c, 0x6f, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6c, 0x6f, 0x67, 0x32, 0x5c, 0x0a, 0x07, 0x50, 0x6f, 0x64, 0x4c, 0x6f, 0x67,
	0x73, 0x12, 0x25, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x12, 0x0b, 0x2e, 0x70, 0x6c,
	0x6f, 0x67, 0x67, 0x69, 0x2e, 0x50, 0x6f, 0x64, 0x1a, 0x0e, 0x2e, 0x70, 0x6c, 0x6f, 0x67, 0x67,
	0x69, 0x2e, 0x50, 0x6f, 0x64, 0x4c, 0x6f, 0x67, 0x12, 0x2a, 0x0a, 0x09, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x4c, 0x6f, 0x67, 0x12, 0x0b, 0x2e, 0x70, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x2e, 0x50,
	0x6f, 0x64, 0x1a, 0x0e, 0x2e, 0x70, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x2e, 0x50, 0x6f, 0x64, 0x4c,
	0x6f, 0x67, 0x30, 0x01, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x74, 0x6a, 0x6f, 0x6c, 0x6f, 0x6c, 0x6f, 0x2f, 0x70, 0x6c, 0x6f, 0x67, 0x67,
	0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x6f, 0x67, 0x67, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_ploggi_ploggi_proto_rawDescOnce sync.Once
	file_pkg_api_ploggi_ploggi_proto_rawDescData = file_pkg_api_ploggi_ploggi_proto_rawDesc
)

func file_pkg_api_ploggi_ploggi_proto_rawDescGZIP() []byte {
	file_pkg_api_ploggi_ploggi_proto_rawDescOnce.Do(func() {
		file_pkg_api_ploggi_ploggi_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_ploggi_ploggi_proto_rawDescData)
	})
	return file_pkg_api_ploggi_ploggi_proto_rawDescData
}

var file_pkg_api_ploggi_ploggi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_api_ploggi_ploggi_proto_goTypes = []interface{}{
	(*Pod)(nil),    // 0: ploggi.Pod
	(*PodLog)(nil), // 1: ploggi.PodLog
}
var file_pkg_api_ploggi_ploggi_proto_depIdxs = []int32{
	0, // 0: ploggi.PodLogs.GetLog:input_type -> ploggi.Pod
	0, // 1: ploggi.PodLogs.StreamLog:input_type -> ploggi.Pod
	1, // 2: ploggi.PodLogs.GetLog:output_type -> ploggi.PodLog
	1, // 3: ploggi.PodLogs.StreamLog:output_type -> ploggi.PodLog
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_ploggi_ploggi_proto_init() }
func file_pkg_api_ploggi_ploggi_proto_init() {
	if File_pkg_api_ploggi_ploggi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_api_ploggi_ploggi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_ploggi_ploggi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodLog); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_ploggi_ploggi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_ploggi_ploggi_proto_goTypes,
		DependencyIndexes: file_pkg_api_ploggi_ploggi_proto_depIdxs,
		MessageInfos:      file_pkg_api_ploggi_ploggi_proto_msgTypes,
	}.Build()
	File_pkg_api_ploggi_ploggi_proto = out.File
	file_pkg_api_ploggi_ploggi_proto_rawDesc = nil
	file_pkg_api_ploggi_ploggi_proto_goTypes = nil
	file_pkg_api_ploggi_ploggi_proto_depIdxs = nil
}
